version: '3.1'

volumes:
  msa_db_data:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul
    volumes:
      - msa_db_data:/var/lib/laitmysql/data
    restart: always
